import type { Company } from './types';

export const sampleCompanies: Company[] = [
  {
    id: 1,
    name: "TechFlow Solutions",
    industry: "Technology",
    size: "51-200",
    location: "San Francisco, CA",
    foundingYear: 2018,
    website: "https://techflowsolutions.com",
    description: "AI-powered workflow automation for enterprise clients",
    tags: ["AI", "Automation", "Enterprise", "SaaS"],
    employees: "150",
    revenue: "$25M",
    status: "Growing"
  },
  {
    id: 2,
    name: "GreenEnergy Dynamics",
    industry: "Energy",
    size: "201-500",
    location: "Austin, TX",
    foundingYear: 2015,
    website: "https://greenergy.com",
    description: "Renewable energy solutions and smart grid technology",
    tags: ["Renewable Energy", "Smart Grid", "Sustainability"],
    employees: "320",
    revenue: "$45M",
    status: "Stable"
  },
  {
    id: 3,
    name: "FinanceBot Inc",
    industry: "Financial Services",
    size: "11-50",
    location: "New York, NY",
    foundingYear: 2020,
    website: "https://financebot.io",
    description: "AI-driven personal finance management platform",
    tags: ["FinTech", "AI", "Personal Finance", "Mobile App"],
    employees: "45",
    revenue: "$8M",
    status: "Growing"
  },
  {
    id: 4,
    name: "HealthTech Innovations",
    industry: "Healthcare",
    size: "101-250",
    location: "Boston, MA",
    foundingYear: 2017,
    website: "https://healthtech-innovations.com",
    description: "Digital health solutions for patient monitoring",
    tags: ["HealthTech", "IoT", "Patient Care", "Digital Health"],
    employees: "180",
    revenue: "$32M",
    status: "Growing"
  },
  {
    id: 5,
    name: "EduLearn Platform",
    industry: "Education",
    size: "51-200",
    location: "Seattle, WA",
    foundingYear: 2019,
    website: "https://edulearn.com",
    description: "Online learning platform with adaptive AI tutoring",
    tags: ["EdTech", "AI", "Online Learning", "Adaptive Learning"],
    employees: "95",
    revenue: "$15M",
    status: "Growing"
  },
  {
    id: 6,
    name: "RetailMax Analytics",
    industry: "Retail",
    size: "251-500",
    location: "Chicago, IL",
    foundingYear: 2014,
    website: "https://retailmax.com",
    description: "Advanced analytics and inventory management for retailers",
    tags: ["Retail Analytics", "Inventory Management", "Big Data"],
    employees: "280",
    revenue: "$52M",
    status: "Stable"
  },
  {
    id: 7,
    name: "CloudSecure Systems",
    industry: "Technology",
    size: "101-250",
    location: "Denver, CO",
    foundingYear: 2016,
    website: "https://cloudsecure.com",
    description: "Cloud security solutions for enterprise applications",
    tags: ["Cloud Security", "Cybersecurity", "Enterprise", "DevSecOps"],
    employees: "165",
    revenue: "$28M",
    status: "Growing"
  },
  {
    id: 8,
    name: "AgriTech Ventures",
    industry: "Agriculture",
    size: "11-50",
    location: "Des Moines, IA",
    foundingYear: 2021,
    website: "https://agritech-ventures.com",
    description: "Precision agriculture using IoT and drone technology",
    tags: ["AgTech", "IoT", "Drones", "Precision Agriculture"],
    employees: "38",
    revenue: "$5M",
    status: "Growing"
  },
  {
    id: 9,
    name: "MediaStream Pro",
    industry: "Media & Entertainment",
    size: "51-200",
    location: "Los Angeles, CA",
    foundingYear: 2018,
    website: "https://mediastreampro.com",
    description: "Video streaming and content delivery network services",
    tags: ["Streaming", "CDN", "Video Technology", "Media"],
    employees: "120",
    revenue: "$22M",
    status: "Growing"
  },
  {
    id: 10,
    name: "LogiChain Solutions",
    industry: "Logistics",
    size: "201-500",
    location: "Memphis, TN",
    foundingYear: 2013,
    website: "https://logichain.com",
    description: "Supply chain optimization and logistics management",
    tags: ["Supply Chain", "Logistics", "Optimization", "B2B"],
    employees: "350",
    revenue: "$68M",
    status: "Stable"
  }
];

export const industries = [
  "Technology",
  "Energy",
  "Financial Services",
  "Healthcare",
  "Education",
  "Retail",
  "Agriculture",
  "Media & Entertainment",
  "Logistics"
];

export const companySizes = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1000+"
];

export const locations = [
  "San Francisco, CA",
  "Austin, TX",
  "New York, NY",
  "Boston, MA",
  "Seattle, WA",
  "Chicago, IL",
  "Denver, CO",
  "Des Moines, IA",
  "Los Angeles, CA",
  "Memphis, TN"
];

export const allTags = [
  "AI",
  "Automation",
  "Enterprise",
  "SaaS",
  "Renewable Energy",
  "Smart Grid",
  "Sustainability",
  "FinTech",
  "Personal Finance",
  "Mobile App",
  "HealthTech",
  "IoT",
  "Patient Care",
  "Digital Health",
  "EdTech",
  "Online Learning",
  "Adaptive Learning",
  "Retail Analytics",
  "Inventory Management",
  "Big Data",
  "Cloud Security",
  "Cybersecurity",
  "DevSecOps",
  "AgTech",
  "Drones",
  "Precision Agriculture",
  "Streaming",
  "CDN",
  "Video Technology",
  "Media",
  "Supply Chain",
  "Logistics",
  "Optimization",
  "B2B"
];